kind: Pod
apiVersion: v1
metadata:
  name: nginx-app
  labels:
    app: app-data
spec:
  nodeSelector:
    kubernetes.io/hostname: "gke-standard-cluster-2-default-pool-babd6f19-z54g"
  volumes:
    - name: app-data
      persistentVolumeClaim:
       claimName: app-data-claim
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: app-data
